### ISSUE TITLE
Dockerhub credential in pipeline

### ISSUE THREAD

**Issue by mjemnawaz** [fireant-bot/fireant#25]
Add or explain how to add a username/password credential for dockerhub on a jenkins instance so that the jenkins pipeline will execute successfully.

**Comment by lewismc** [comment]
@mjemnawaz please document the above ticket otherwise no-one knows what this means. Thank you

**Comment by lewismc** [comment]
Hi @mjemnawaz you can see that I restructured the credential identifier, namely `USE_UPPER_CASE_AND_SEPARATE_WITH_UNDERSCORES`.
We then [reference it as follows](https://github.com/fireant-bot/fireant/blob/main/Jenkinsfile#L24).

**Comment by lewismc** [comment]
You can see it being used in the most recent build
https://ci-builds.apache.org/job/Nutch/job/nutch-fireant/10/console
The build fails as follows
> Using the existing docker config file.Removing blacklisted property: auths$ docker login -u fireant-dockerhub-id -p ******** https://index.docker.io/v1/
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

Please check the credentials you sent me and resend if they are correct.

**Comment by lewismc** [comment]
We are still getting the former
```
Using the existing docker config file.Removing blacklisted property: auths$ docker login -u fireantbot -p ******** https://index.docker.io/v1/

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/jenkins/workspace/Nutch/nutch-fireant@tmp/5b1d081e-d499-45ae-9d82-73c2812bbfc8/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```
@mjemnawaz can you please take a look and let me know if you can come to any solution?

**Comment by lewismc** [comment]
https://ci-builds.apache.org/job/Nutch/job/nutch-fireant/11/console

**Comment by lewismc** [comment]
OK the pipeline is successful
https://hub.docker.com/r/fireantbot/fireant
