### ISSUE TITLE
Updates to plugin ivy.xml files also need to update the corresponding plugin.xml files

### ISSUE THREAD

**Issue by lewismc** [fireant-bot/fireant#64]
@leetheod @rgw17 remember when we manually upgraded the dependencies on the Nutch side???
We had to follow the [howto_upgrade_tika.txt](https://github.com/apache/nutch/blob/master/src/plugin/parse-tika/howto_upgrade_tika.txt) for example.
Can you guys have a look at what it would take to update main.py to run the necessary logic to do that?
This requires running `ant` on the plugin directory and then some unix tools i.e. `sed` and `ls`.

**Comment by lewismc** [comment]
@leetheod @rgw17 are you guys able to take a look? If not, then I will work this one. Thanks

**Comment by leetheod** [comment]
@lewismc randall and I will take a look on friday! We will let you know then.
