### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by leetheod** [fireant-bot/fireant#8]
I'm currently trying to work out documentation for portions of Fireant with readthedocs.io and sphinx. More specifically, I aim to document what Fireant does and how it works, as well as instructions on how to properly install / run it. If there's a need or want for more information (Jenkins / Docker / Unit Test documentation) as well, I can look into that. I'll most likely need to connect with all team members to get a better understanding on how I should document different aspects. 

The only documentation I currently posses is the Updating Dependencies Tutorial which I based off of Nutch Confluence pages. It's currently formatted as a google doc in our team drive. Since Fireant is an automated service, I'm not sure whether this documentation is necessary. Let me know if I should still make a PR for this / update the documentation with readthedocs

**Comment by lewismc** [comment]
@leetheod thanks for registering this issue. Please hyperlink to the _Updating Dependencies Tutorial_ you've referenced above. I've never seen it before. 
I don't think that tutorial will be relevant for updating the dependencies with Fireant... so lets just focus on the Fireant documentation.
Specifically, I'm interested in you documenting the [Dockerfilke](https://github.com/fireant-bot/fireant/blob/main/Dockerfile) (which has still not been updated to the JDK11 upgrade I performed several weeks ago) adequately.
I've used readthedocs.io and sphinx to product documentation for loads of projects so I am very familiar with both.
For example, documentation for the [podaacpy](https://github.com/nasa/podaacpy) project can be found [here](https://podaacpy.readthedocs.io/en/latest/).
The podaacpy project will give you ever piece of guidance you need to implement adequate documentation.
Thanks

**Comment by leetheod** [comment]
_Updating Dependencies Tutorial_: https://docs.google.com/document/d/1YgFjg-EVRMW5pCsUUin1nXFkp-8zSvtaV4KVfxXkh8g/edit?usp=sharing

Sounds good, I will look into the podaacpy project documentation and apply it here.

**Comment by lewismc** [comment]
Please go ahead and update the README to begin with.

**Comment by lewismc** [comment]
At the meeting on 04/16/2021 we decided NOT to move forward with Sphinx documentation. Instead we will ensure there is a detailed README which builds on the existing content on the [wiki](https://github.com/fireant-bot/fireant/wiki).
